version: '3'
services:
  mysql-ecommerce-test1:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=ecommerce
    volumes:
      - ./data/mysql-test1/:/var/lib/mysql
  mysql-ecommerce-test2:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=ecommerce
    volumes:
      - ./data/mysql-test2/:/var/lib/mysql


networks:
  default:
    driver: bridge