spring:
  application:
    name: e-commerce
  profiles:
    active: local
  datasource:
    name: ecommerce
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    properties:
      auto.create.topics.enable: false
      security.protocol: PLAINTEXT
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      auto:
        offset.reset: earliest
        register.schemas: false
        create.topics.enable: false
      use.latest.version: true
      basic.auth.credentials.source: USER_INFO
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        enable-auto-commit: false
    listener:
      ack-mode: manual

e-commerce-api:
  test:
    topic-name: test-topic

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: ecommerce
    password: ecommerce
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true # SQL 포맷팅
      highlight_sql: true # ANSI 코드에 색을 나타낸다
      use_sql_comments: true # SQL 내부에 /* */ 주석 추가
  sql:
    init:
      mode: never
      data-locations: classpath:data-init.sql

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: method

logging:
  level:
    org.redisson: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

---
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create